ALTER TABLE "AdminUser"
ADD COLUMN IF NOT EXISTS "role" TEXT NOT NULL DEFAULT 'admin',
ADD COLUMN IF NOT EXISTS "dataLocaleAccess" TEXT NOT NULL DEFAULT 'all';

ALTER TABLE "SpinData"
ADD COLUMN IF NOT EXISTS "locale" TEXT NOT NULL DEFAULT 'en';
